const app=document.getElementById('app');
let sb=null, me=null, data={lessons:[],exams:[],pdfs:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
function ready(){return window.KH_CONFIG && !window.KH_CONFIG.SUPABASE_URL.includes('PASTE_') && window.supabase}
async function db(p){if(!sb)throw Error('لم يتم إعداد قاعدة البيانات بعد');return p}
async function init(){
 if(!ready()){setupScreen();return}
 sb=window.supabase.createClient(KH_CONFIG.SUPABASE_URL,KH_CONFIG.SUPABASE_ANON_KEY);
 const {data:{session}}=await sb.auth.getSession();
 if(session) await load(); else login();
 sb.auth.onAuthStateChange((_e,s)=>{if(!s){me=null;login()}})
}
function setupScreen(){app.innerHTML=`<div class="login"><div class="login-brand"><div class="brand-inner"><div class="logo">خ</div><h1>الخوارزمي محمد جمال</h1><p>AL-KHWARIZMI MOHAMED GAMAL</p><p>معاً نحو التفوق في الرياضيات</p></div></div><div class="login-card"><h2>إعداد المنصة</h2><p class="muted">النسخة دي جاهزة لـ Vercel + Supabase، لكن لازم تضيف بيانات Supabase في ملف <b>public/config.js</b> قبل النشر.</p><div class="card" style="margin-top:20px"><strong>المطلوب</strong><ol><li>إنشاء مشروع في Supabase.</li><li>تشغيل ملف <b>supabase/schema.sql</b>.</li><li>نسخ Project URL و Anon Key إلى <b>public/config.js</b>.</li></ol></div></div></div>`}
function login(){app.innerHTML=`<div class="login"><div class="login-brand"><div class="brand-inner"><div class="logo">خ</div><h1>الخوارزمي محمد جمال</h1><p>AL-KHWARIZMI MOHAMED GAMAL</p><p>معاً نحو التفوق في الرياضيات</p></div></div><div class="login-card"><h2>تسجيل الدخول</h2><p class="muted">مرحباً بك مجدداً .. نورتنا</p><form id="loginForm"><div class="field"><label>البريد الإلكتروني</label><input id="identifier" type="email" required autocomplete="username"></div><div class="field"><label>كلمة المرور</label><input id="password" type="password" required autocomplete="current-password"></div><button class="btn btn-primary" style="width:100%">دخول</button></form><div class="login-switch"><span class="muted">ليس لديك حساب؟</span> <button class="btn btn-light" onclick="register()">إنشاء حساب</button></div><p class="muted" style="font-size:12px;margin-top:25px">حساب المدرس يُنشأ من Supabase ثم يُعطى دور admin من جدول profiles.</p></div></div>`;
 document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();try{const {error}=await sb.auth.signInWithPassword({email:identifier.value.trim(),password:password.value});if(error)throw error;await load()}catch(e){toast(e.message||'تعذر تسجيل الدخول')}}}
function register(){app.innerHTML=`<div class="login"><div class="login-brand"><div class="brand-inner"><div class="logo">خ</div><h1>انضم إلى الخوارزمي</h1><p>تعلم الرياضيات بأسلوب أبسط ومنظم.</p></div></div><div class="login-card"><h2>إنشاء حساب طالب</h2><form id="reg"><div class="field"><label>الاسم</label><input id="rname" required></div><div class="field"><label>البريد الإلكتروني</label><input id="remail" type="email" required></div><div class="field"><label>كلمة المرور</label><input id="rpass" type="password" minlength="6" required></div><div class="field"><label>الصف</label><select id="rgrade"><option>الأولى الثانوية</option><option selected>الثانية الثانوية باكالوريا</option><option>الثالثة الثانوية</option></select></div><button class="btn btn-primary" style="width:100%">إنشاء الحساب</button></form><div class="login-switch"><button class="btn btn-light" onclick="login()">العودة لتسجيل الدخول</button></div></div></div>`;
 reg.onsubmit=async e=>{e.preventDefault();try{const {data:user,error}=await sb.auth.signUp({email:remail.value.trim(),password:rpass.value,options:{data:{name:rname.value.trim(),grade:rgrade.value}}});if(error)throw error;if(user.user){toast('تم إنشاء الحساب. إذا طُلب تأكيد البريد، افتح رسالة التأكيد ثم سجّل الدخول.');setTimeout(login,800)}}catch(e){toast(e.message||'تعذر إنشاء الحساب')}}}
async function load(){try{const {data:u,error:ue}=await sb.auth.getUser();if(ue||!u.user)throw Error('انتهت الجلسة');const {data:p,error:pe}=await sb.from('profiles').select('*').eq('id',u.user.id).single();if(pe)throw pe;me=p;const [l,e,pdfs]=await Promise.all([sb.from('lessons').select('*').order('created_at',{ascending:false}),sb.from('exams').select('*').order('created_at',{ascending:false}),sb.from('pdfs').select('*').order('created_at',{ascending:false})]);data={lessons:l.data||[],exams:e.data||[],pdfs:pdfs.data||[]};renderHome()}catch(e){console.error(e);toast('تعذر تحميل بيانات المنصة: '+(e.message||''));login()}}
function layout(content,active='home'){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="side-brand"><div class="logo">خ</div><div><strong>الخوارزمي محمد جمال</strong><small>AL-KHWARIZMI</small></div></div><nav class="nav">${nav('home','الرئيسية','⌂',active)}${nav('lessons','الدروس','▣',active)}${nav('exams','الاختبارات','✓',active)}${nav('pdfs','الواجبات والامتحانات','▤',active)}${me.role==='admin'?nav('admin','لوحة الأدمن','⚙',active):''}${nav('account','حسابي','◉',active)}<button onclick="logout()">↪ تسجيل الخروج</button></nav><div class="side-quote">الجهد اليوم .. هو النجاح غداً</div></aside><main class="main"><div class="topbar"><input class="search" placeholder="ابحث عن درس أو تمرين..." oninput="searchAll(this.value)"><div class="profile-mini"><div><strong>${esc(me.name)}</strong><div class="muted">${me.role==='admin'?'مدرس / أدمن':'طالب'}</div></div><div class="avatar">${esc((me.name||'ط')[0])}</div></div></div>${content}<div class="footer">الخوارزمي محمد جمال · رياضيات .. تصنع مستقبلك</div></main></div>`}
function nav(id,label,icon,active){return `<button class="${active===id?'active':''}" onclick="go('${id}')">${icon} &nbsp; ${label}</button>`}
function go(id){if(id==='home')renderHome();if(id==='lessons')lessons();if(id==='exams')exams();if(id==='pdfs')pdfs();if(id==='admin')adminPage();if(id==='account')account()}
function renderHome(){const pct=65;layout(`<section class="hero"><div><h1>مرحباً بك في منصة الخوارزمي محمد جمال</h1><p>رحلتك نحو التفوق في الرياضيات تبدأ من هنا.</p><button class="btn" style="background:#fff;color:#0d6efd" onclick="go('lessons')">ابدأ التعلم ←</button></div><div class="hero-art">∫ π √ x²</div></section><div class="grid"><div class="card feature"><div class="iconbox">✓</div><h3>اختبارات تفاعلية</h3><p class="muted">اختبر نفسك وتابع تقدمك</p></div><div class="card feature"><div class="iconbox">▶</div><h3>دروس بالفيديو</h3><p class="muted">شرح مبسط لكل الدروس</p></div><div class="card feature"><div class="iconbox">▣</div><h3>ملاحظات وملخصات</h3><p class="muted">محتوى مركز ومنظم</p></div><div class="card feature"><div class="iconbox">↗</div><h3>تتبع تقدمك</h3><p class="muted">شاهد تطور مستواك</p></div></div><div class="section-title"><h2>اختر صفك الدراسي</h2></div><div class="classes">${['الأولى الثانوية','الثانية الثانوية باكالوريا','الثالثة الثانوية'].map(x=>`<div class="class-card ${x===me.grade?'active':''}"><h3>${x}</h3><p>الرياضيات</p><button class="btn ${x===me.grade?'':'btn-light'}" onclick="go('lessons')">ابدأ الآن ←</button></div>`).join('')}</div><div class="section-title"><h2>إحصائياتك</h2></div><div class="card"><div class="stats"><div class="stat"><strong>12</strong><span class="muted">إنجاز</span></div><div class="stat"><strong>850</strong><span class="muted">نقطة</span></div><div class="stat"><strong>8</strong><span class="muted">دروس مكتملة</span></div><div class="stat"><strong>4</strong><span class="muted">اختبارات مجتازة</span></div></div><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><div style="display:flex;justify-content:space-between"><strong>مستواك الحالي</strong><b>${pct}%</b></div><div class="progress"><i style="width:${pct}%"></i></div><p class="muted">لا تتوقف .. فأنت أقرب مما تظن.</p></div>`,'home')}
function lessons(){const ls=data.lessons.length?data.lessons:[{title:'المتجهات في الفراغ',unit:'الهندسة',duration:'18:45'},{title:'حل معادلات الدرجة الثانية',unit:'الجبر',duration:'25:30'},{title:'الاشتقاق وتطبيقاته',unit:'التفاضل',duration:'22:17'},{title:'المصفوفات',unit:'الجبر',duration:'16:12'}];layout(`<div class="section-title"><h2>الدروس</h2><span class="muted">محتوى منظم لكل صف</span></div><div class="lesson-grid">${ls.map(l=>`<div class="card"><div class="lesson-thumb">▶</div><h3>${esc(l.title)}</h3><p class="muted">${esc(l.grade||l.unit||'رياضيات')} · ${esc(l.duration||'')}</p>${l.video_url?`<a class="btn btn-light" href="${esc(l.video_url)}" target="_blank">مشاهدة الدرس</a>`:'<button class="btn btn-light" onclick="toast(\'سيتم فتح الدرس عند إضافة رابط الفيديو\')">مشاهدة الدرس</button>'}</div>`).join('')}</div>`,'lessons')}
function exams(){const xs=data.exams.filter(x=>x.published||me.role==='admin');layout(`<div class="section-title"><h2>الاختبارات</h2></div><div class="admin-list">${xs.length?xs.map(e=>`<div class="item"><div><strong>${esc(e.title)}</strong><div class="muted">${esc(e.grade)} · ${esc(e.unit||'عام')} · ${e.questions||0} سؤال · ${e.duration||0} دقيقة</div></div><span class="badge ${e.published?'green':'red'}">${e.published?'منشور':'مسودة'}</span></div>`).join(''):'<div class="card empty">لا توجد اختبارات منشورة حالياً.</div>'}</div>`,'exams')}
function pdfs(){const ps=data.pdfs.filter(p=>p.published||me.role==='admin');layout(`<div class="section-title"><h2>الواجبات والامتحانات PDF</h2>${me.role==='admin'?'<button class="btn btn-primary" onclick="pdfModal()">+ رفع PDF</button>':''}</div><div class="admin-list">${ps.length?ps.map(p=>`<div class="item"><div><strong>${esc(p.title)}</strong><div class="muted">${esc(p.type)} · ${esc(p.grade)} · ${esc(p.unit)}</div><small>${esc(p.description||'')}</small></div><div class="actions"><span class="badge ${p.published?'green':'red'}">${p.published?'منشور':'مسودة'}</span><a class="btn btn-light" href="${esc(p.url)}" target="_blank">فتح PDF</a>${me.role==='admin'?`<button class="btn btn-danger" onclick="deletePdf('${p.id}')">حذف</button>`:''}</div></div>`).join(''):'<div class="card empty">لا توجد ملفات PDF حتى الآن.</div>'}</div>`,'pdfs')}
function adminPage(){layout(`<div class="section-title"><h2>لوحة تحكم الأدمن</h2><span class="badge">محمد جمال البدري</span></div><div class="admin-grid"><div class="card"><h3>رفع واجب أو امتحان PDF</h3><p class="muted">ارفع الملف وحدد الصف والوحدة ونوع المحتوى ثم انشره للطلاب.</p><button class="btn btn-primary" onclick="pdfModal()">+ رفع ملف PDF</button></div><div class="card"><h3>إضافة درس فيديو</h3><form id="lessonForm"><div class="field"><label>اسم الدرس</label><input id="ltitle" required></div><div class="row"><div class="field"><label>الوحدة</label><input id="lunit"></div><div class="field"><label>المدة</label><input id="lduration" placeholder="18:45"></div></div><div class="field"><label>الصف</label><select id="lgrade"><option>الأولى الثانوية</option><option selected>الثانية الثانوية باكالوريا</option><option>الثالثة الثانوية</option></select></div><div class="field"><label>رابط الفيديو</label><input id="lurl" placeholder="https://..."></div><button class="btn btn-primary">إضافة الدرس</button></form></div></div><div class="section-title"><h2>آخر ملفات PDF</h2></div><div class="admin-list">${data.pdfs.length?data.pdfs.slice(0,8).map(p=>`<div class="item"><div><strong>${esc(p.title)}</strong><div class="muted">${esc(p.type)} · ${esc(p.grade)} · ${esc(p.unit)}</div></div><div class="actions"><span class="badge ${p.published?'green':'red'}">${p.published?'منشور':'مسودة'}</span><button class="btn btn-danger" onclick="deletePdf('${p.id}')">حذف</button></div></div>`).join(''):'<div class="card empty">لا توجد ملفات بعد.</div>'}</div>`,'admin');document.getElementById('lessonForm').onsubmit=async e=>{e.preventDefault();try{const {error}=await sb.from('lessons').insert({title:ltitle.value.trim(),unit:lunit.value.trim(),duration:lduration.value.trim(),grade:lgrade.value,video_url:lurl.value.trim(),created_by:me.id});if(error)throw error;toast('تمت إضافة الدرس');await load();adminPage()}catch(e){toast(e.message)}}}
function account(){layout(`<div class="section-title"><h2>حسابي</h2></div><div class="card"><div class="profile-mini"><div class="avatar" style="width:70px;height:70px;font-size:26px">${esc((me.name||'ط')[0])}</div><div><h2>${esc(me.name)}</h2><p class="muted">${esc(me.email)} · ${esc(me.grade||'')}</p></div></div></div>`,'account')}
function pdfModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal"><div class="modal"><div class="section-title"><h2>رفع ملف PDF</h2><button class="btn btn-light" onclick="modal.remove()">إغلاق</button></div><form id="pdfForm"><div class="field"><label>عنوان الملف</label><input id="ptitle" required></div><div class="row"><div class="field"><label>النوع</label><select id="ptype"><option>واجب</option><option>امتحان</option><option>ملخص</option></select></div><div class="field"><label>الصف</label><select id="pgrade"><option>الأولى الثانوية</option><option selected>الثانية الثانوية باكالوريا</option><option>الثالثة الثانوية</option></select></div></div><div class="field"><label>الوحدة / الدرس</label><input id="punit" required></div><div class="field"><label>الوصف</label><textarea id="pdesc" rows="3"></textarea></div><div class="field"><label>ملف PDF</label><input id="pfile" type="file" accept="application/pdf,.pdf" required></div><label style="display:flex;gap:8px;align-items:center;margin:12px 0"><input id="ppub" type="checkbox" checked> نشر الملف للطلاب فوراً</label><button class="btn btn-primary" style="width:100%">رفع ونشر</button></form></div></div>`);pdfForm.onsubmit=uploadPdf}
async function uploadPdf(e){e.preventDefault();const file=pfile.files[0];if(!file||file.type!=='application/pdf')return toast('اختر ملف PDF صحيح');if(file.size>20*1024*1024)return toast('حجم الملف يجب ألا يتجاوز 20MB');try{const safe=file.name.replace(/[^\w\-.\u0600-\u06FF ]/g,'_');const path=`${crypto.randomUUID()}-${safe}`;const up=await sb.storage.from('pdfs').upload(path,file,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const {data:pub}=sb.storage.from('pdfs').getPublicUrl(path);const ins=await sb.from('pdfs').insert({title:ptitle.value.trim(),type:ptype.value,grade:pgrade.value,unit:punit.value.trim(),description:pdesc.value.trim(),url:pub.publicUrl,storage_path:path,published:ppub.checked,created_by:me.id});if(ins.error)throw ins.error;toast('تم رفع الملف بنجاح');modal.remove();await load();adminPage()}catch(e){toast(e.message||'تعذر رفع الملف')}}
async function deletePdf(id){if(!confirm('حذف هذا الملف؟'))return;try{const row=data.pdfs.find(x=>x.id===id);if(row?.storage_path)await sb.storage.from('pdfs').remove([row.storage_path]);const {error}=await sb.from('pdfs').delete().eq('id',id);if(error)throw error;toast('تم الحذف');await load();adminPage()}catch(e){toast(e.message)}}
function searchAll(q){if(!q)return;const hit=[...(data.lessons||[]),...(data.pdfs||[]),...(data.exams||[])].filter(x=>(x.title||'').includes(q));if(hit.length)toast(`تم العثور على ${hit.length} نتيجة`)}
async function logout(){await sb.auth.signOut();me=null;login()}
init();
